CREATE DATABASE bookstp;
USE bookstp;

DROP TABLE IF EXISTS Auteur ;
CREATE TABLE Auteur (Id_Auteur INT(25) AUTO_INCREMENT NOT NULL,
Prenom_Auteur VARCHAR(25),
Nom_Auteur VARCHAR(25),
Birthday_Auteur DATE,
Id_City integer(25),
PRIMARY KEY (Id_Auteur)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Livre ;
CREATE TABLE Livre (Id_Livre INT(25) AUTO_INCREMENT NOT NULL,
Title_Livre VARCHAR(25),
Genre_Livre VARCHAR(25),
Descriptif_Livre VARCHAR(255),
Id_Auteur integer(25),
Id_Editeur integer(25),
Id_Genre integer(25),
PRIMARY KEY (Id_Livre)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Editeur ;
CREATE TABLE Editeur (Id_Editeur INT(25) AUTO_INCREMENT NOT NULL,
Name_Editeur VARCHAR(25),
PRIMARY KEY (Id_Editeur)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Magasin ;
CREATE TABLE Magasin (Id_Magasin INT(25) AUTO_INCREMENT NOT NULL,
Name_Magasin VARCHAR(25),
Id_City integer(25),
PRIMARY KEY (Id_Magasin)) ENGINE=InnoDB;

DROP TABLE IF EXISTS City ;
CREATE TABLE City (Id_City INT(25) AUTO_INCREMENT NOT NULL,
Name_City VARCHAR(25),
PRIMARY KEY (Id_City)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Genre ;
CREATE TABLE Genre (Id_Genre INT(25) AUTO_INCREMENT NOT NULL,
Name_Genre VARCHAR(25),
PRIMARY KEY (Id_Genre)) ENGINE=InnoDB;

DROP TABLE IF EXISTS Vendre ;
CREATE TABLE Vendre (Id_Magasin integer(25) AUTO_INCREMENT NOT NULL,
Id_Livre integer(25) NOT NULL,
Sell_Price_Vendre FLOAT(3),
PRIMARY KEY (Id_Magasin)) ENGINE=InnoDB;

ALTER TABLE Auteur ADD CONSTRAINT FK_Id_City FOREIGN KEY (Id_City) REFERENCES City (Id_City);
ALTER TABLE Livre ADD CONSTRAINT FK_Id_Auteur FOREIGN KEY (Id_Auteur) REFERENCES Auteur (Id_Auteur);
ALTER TABLE Livre ADD CONSTRAINT FK_Id_Editeur FOREIGN KEY (Id_Editeur) REFERENCES Editeur (Id_Editeur);
ALTER TABLE Livre ADD CONSTRAINT FK_Id_Genre FOREIGN KEY (Id_Genre) REFERENCES Genre (Id_Genre);
ALTER TABLE Magasin ADD CONSTRAINT FK_Id_City FOREIGN KEY (Id_City) REFERENCES City (Id_City);
ALTER TABLE Vendre ADD CONSTRAINT FK_Vendre_Id_Magasin FOREIGN KEY (Id_Magasin) REFERENCES Magasin (Id_Magasin);
ALTER TABLE Vendre ADD CONSTRAINT FK_Vendre_Id_Livre FOREIGN KEY (Id_Livre) REFERENCES Livre (Id_Livre);
